# Generated by Django 4.2.3 on 2023-07-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('IT', 'IT'), ('Non IT', 'Non IT'), ('mobiles', 'mobiles')], max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
